a = ['a', 'b', 'c', 'd', 'a', 'c', 6]
#a.sort()
#a.sort(reverse=True)
#a.reverse()
a.insert(0,'k')
b = set(['a', 'b', 'c', 'd', 'a', 'c'])
print(a, b)
print(a.index('a'))
print(len(a), a.count(6))
a.remove('k')
print(a)
del a[3]
print(a)
k1 = a.pop()
print(k1)
a.append('z')
print(a)
a.clear()
print(a)